name: "clip_vision"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [3, 224, 224]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [512]
  }
]

name: "clip_text"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "INPUT__0"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [512]
  }
]